export const PHASES = {
  ON_TURN_START: "ON_TURN_START",
  PRE_MOVE: "PRE_MOVE",
  ON_DAMAGE: "ON_DAMAGE",
  POST_DAMAGE: "POST_DAMAGE",
  POST_MOVE: "POST_MOVE",
  ON_FAINT: "ON_FAINT",
  POST_FAINT: "POST_FAINT",
  TURN_END: "TURN_END",
};

export const PRIORITY = {
  FIELD: 100,
  WEATHER: 80,
  STATUS: 60,
  ABILITY: 40,
  ITEM: 20,
  NORMAL: 0,
};
