export const PHASES = {
  ON_TURN_START: "ON_TURN_START",
  PRE_MOVE: "PRE_MOVE",
  ON_DAMAGE: "ON_DAMAGE",
  POST_DAMAGE: "POST_DAMAGE",
  POST_MOVE: "POST_MOVE",
  ON_FAINT: "ON_FAINT",
  TURN_END: "TURN_END",
};

export const PRIORITY = {
  HIGH_ABILITY: 100,
  WEATHER: 50,
  ITEM: 20,
  LOW_ABILITY: 10,
  NORMAL: 0,
};
