export const COMMANDS = {
  SHOW_MESSAGE: "SHOW_MESSAGE",
  WAIT: "WAIT",
  UPDATE_HP_BAR: "UPDATE_HP_BAR",
  UPDATE_EXP_BAR: "UPDATE_EXP_BAR",
  LEVEL_UP_ANIMATION: "LEVEL_UP_ANIMATION",
  STAT_UPDATE_ANIMATION: "STAT_UPDATE_ANIMATION",
  RESOLVE_FAINT: "RESOLVE_FAINT",
  RESOLVE_END_BATTLE: "RESOLVE_END_BATTLE",
  EVOLUTION_START_ANIMATION: "EVOLUTION_START_ANIMATION",
  EVOLUTION_COMPLETE_ANIMATION: "EVOLUTION_COMPLETE_ANIMATION",
  PAUSE_QUEUE: "PAUSE_QUEUE",
};
